### ISSUE TITLE
score is nan

### ISSUE THREAD

**Issue by sakatakate** [kamata1729/QATM_pytorch#4]
ソースコードを共有していただきありがとうございます。
お伺いしたいことがあります。
デモのテンプレートマッチングはおこなうことができました。
そこで自分の画像とテンプレートでマッチングを行ったところ以下のようになりました。
![Screenshot from 2019-08-06 16-27-51](https://user-images.githubusercontent.com/53811776/62519898-6f4d7400-b867-11e9-8b8a-c12a409810b6.png)
![Screenshot from 2019-08-06 16-28-33](https://user-images.githubusercontent.com/53811776/62519906-71173780-b867-11e9-92db-dda96c40aa4e.png)

詳しく見るとrun_one_sample関数下の
val = model(template, image, image_name)でvalがnanと返ってきました。
どのような原因が考えられるでしょうか。
アドバイスいただけるとありがたいです。

追加情報として
テンプレートとマッチング画像の拡張子はdemoのときと同じですが、サイズはテンプレートしかおなじではありません。
また、テンプレートはマッチング画像から切り取ったものではなく、人間の目で見てもテンプレートがマッチング画像に含まれているか判断が困難な画像を使っています。

**Comment by sakatakate** [comment]
解決しました。
おそらくサンプル画像に黒の領域が含まれるとNANが返ってくるようでした

**Comment by NygmaLin** [comment]
@sakatakate does the black area means the pixel of 0 gray value？ my template and raw image with the pixel of 1 gray value also has this issue
